[package]
name = "safaricomalm"
version = "0.1.0"
authors = ["Sisa Philip"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = { version = "0.11.3", features = ["hal"] }


